name: healthy_fit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  floating_navbar: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_round_slider: ^1.0.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  go_router: ^14.6.2
  iconly: ^1.0.1
  icons_launcher: ^3.0.0
  intl: ^0.20.1
  intro_screen_onboarding_flutter: ^1.0.0
  meta: ^1.15.0
  screenutil_module: ^1.1.0
  shared_preferences: ^2.3.4
  shimmer: ^3.0.0
  sleek_circular_slider: ^2.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/images/green_slogan.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
      
flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500

        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 300

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_assets.dart
  field_prefix: null
